CREATE DATABASE apr24th;

use apr24th;

exec sp_help fact;
exec sp_help [Location];
exec sp_help [Product];

select * from fact;
select * from [Location];
select * from [Product];


-- 1. Display the number of states present in the LocationTable
SELECT COUNT(DISTINCT [State]) FROM [Location];

select Count (distinct State) as noofstates from Location;

-- 2.How many products are of regular type?
SELECT COUNT(*) FROM [Product] WHERE [Type] = 'Regular';

-- 3. How much spending has been done on marketing of product ID 1?
select Marketing from fact where ProductId=1;

-- FINAL ANSWER - spending means total marketing
select sum(Marketing) as total_spending from fact where ProductId=1;

-- 4. What is the minimum sales of a product?
select ProductId, MIN(sales) as min_sales
from fact
group by ProductId; 

-- No, they are asking minimum sales of Products (overall) not a product
select min(Sales) as min_sales from fact;

-- 5. Display the max Cost of Good Sold (COGS).
select max(cogs) as max_cogs from fact;

-- 6. Display the details of the product where product type is coffee. 
select * from [Product] where Product_Type = 'Coffee';

-----------------------------------------------------------------------------------

-- Answers given in class

--1. Display the number of states present in the LocationTable
select Count (distinct State) as noofstates from Location
--2.How many products are of regular type?
select * from Product where Type='Regular'
select COUNT(*) as cnt from Product where Type='regular'
--3.How much spending has been done on marketing of product ID 1?
select sum(Marketing) as total_speding from fact where ProductId=1
--4. What is the minimum sales of a products?
select min(Sales) as min_Sales from fact
--5. Display the max Cost of Good Sold (COGS).
select MAX(COGS) as max_cogs from fact
--6. Display the details of the product where product type is coffee. 
select * from Product where Product_Type='Coffee'

-------------------------------------------------------------------------------------

-- 7. Display the details where total expenses are greater than 40. 
select * from fact where Total_Expenses > 40;

--8. What is the average sales in area code 719?
select avg(sales) as avg_sales from fact where Area_Code = 719;

--9. Find out the total profit generated by Colorado state.
select * from fact;
select * from Location;

select sum(Profit)
from fact F
join [Location] L
on F.Area_Code = L.Area_Code
where L.[State] = 'Colorado';

-- trainer's answer
select sum(Profit) from fact
inner join Location
on fact.Area_Code = Location.Area_Code
where State = 'Colorado';


-- 10. Display the average inventory for each product ID.
select ProductId, avg(Inventory) as avg_inventory from fact group by ProductId;

-- trainer used order by for more clarity to view results
select ProductId, avg(Inventory) as avg_inventory from fact
group by ProductId
order by ProductId;


-- 11. Display state in a sequential order in a Location Table.
select distinct [State] from [Location] order by [State];

-- 12. Display the average budget of the Product where the average budget margin should be greater than 100.
-- BUDGET not there, so we take BUDGET MARGIN in select to display
select ProductId, avg(budget_margin) as avg_budget
from fact
group by ProductId
having avg(budget_margin) > 100;

--13. What is the total sales done on date 2010-01-01?
select sum(Sales) as total_sales from fact where [Date] = '2010-01-01';


------------------------------------------------------------------------

-- answers shared from class

--7. Display the details where total expenses are greater than 40. 
select * from fact where Total_Expenses>40
--8. What is the average sales in area code 719?
select AVG(Sales) as avg_sales from fact
where Area_Code=719
--9. Find out the total profit generated by Colorado state.
select sum(Profit) as total_profit from fact
inner join Location
on fact.Area_Code=Location.Area_Code
where State='Colorado'
--10. Display the average inventory for each product ID.
select ProductId,avg(Inventory) as avg_inventory from fact
group by ProductId
order by ProductId
--11. Display state in a sequential order in a Location Table.
select distinct State from Location order by State
--12. Display the average budget Margin of the Product where the average budget margin should be greater than 100.
select ProductId,AVG(Budget_Margin) as avg_budget from fact
group by ProductId
having avg(Budget_Margin)>100
--13. What is the total sales done on date 2010-01-01?
select sum(sales) as total_sales from fact
where date='2010-01-01'

-------------------------------------------------------------------------------------------


---- 25th april 2025
-- 14. Display the average total expense of each product ID on an individual date.
Select ProductId, Date, avg(Total_Expenses) as avg_total_expense
from fact
group by ProductId, Date;

-- trainer's answer
select ProductId,Date,AVG(Total_Expenses) as avg_te from fact
group by ProductId,Date
order by ProductId,Date;



-- 15. Display the table with the following attributes 
-- such as date, productID, product_type, product, sales, profit, state, area_code
select Date, P.ProductId, Product_Type, Product, Sales, Profit, State, L.Area_Code
from fact F
join Product P
on F.ProductId = P.ProductId
join Location L
on F.Area_Code = L.Area_Code;


-- trainer's answer
-- using product.productId since product table is main table for that product id
-- same applies to area code
-- productId and area code are just foreign key columns in fact table
select Date,Product.ProductId,Product_Type,Product,Sales,Profit,State,Location.Area_Code from fact
join Location
on fact.Area_Code=Location.Area_Code
join Product
on fact.ProductId=Product.ProductId;

-- 16. Display the rank without any gap to show the sales wise rank.
select *, DENSE_RANK() OVER (ORDER BY Sales DESC) as sales_rank
from fact;

-- trainer's answer
select sales,dense_RANK() over (Order by Sales desc) as rank_sales from fact;

-- 17. Find the state wise profit and sales. 
select L.[State], SUM(Profit) as Total_profit, SUM(Sales) as Total_sales
from fact F
join [Location] L
on F.Area_Code = L.Area_Code
group by L.[State];

select State, sum(sales) as total_sales, sum(profit) as total_profit
from fact
join Location
on fact.Area_Code = Location.Area_Code
group by State;

-- trainer's answer
select State,Sum(Profit) as totalProfit,Sum(Sales) as totalSales from Location
join fact
on Location.Area_Code=fact.Area_Code
group by State;

-- 18. Find the state wise profit and sales along with the productname.
select L.[State], P.[Product], Sum(F.Profit) as totalProfit,Sum(F.Sales) as totalSales 
from Location L
join fact F
on L.Area_Code=F.Area_Code
join Product P
on P.ProductId = F.ProductId
group by L.[State], P.[Product]
order by L.[State], P.[Product];

select State, Product, Sum(Profit) as totalProfit,Sum(Sales) as totalSales from Location
join fact
on Location.Area_Code=fact.Area_Code
join Product
on Product.ProductId = fact.ProductId
group by State, Product
order by State, Product;

-- trainer's answer
select State,Product,Sum(Profit) as totalProfit,Sum(Sales) as totalSales from Location
join fact
on Location.Area_Code=fact.Area_Code
join Product
on fact.ProductId=Product.ProductId
group by State,Product
order by State,Product;

-- trainer's answer with OPTIONAL not required
-- with rollup and coalesce
select coalesce(state,'S_State'),coalesce(Product,'S_Product'),Sum(Profit) as totalProfit,Sum(Sales) as totalSales from Location
join fact
on Location.Area_Code=fact.Area_Code
join Product
on fact.ProductId=Product.ProductId
group by rollup( State,Product)
order by State,Product;

select coalesce(state,'S_State'),coalesce(Product,'S_Product'),Sum(Profit) as totalProfit,Sum(Sales) as totalSales from Location
join fact
on Location.Area_Code=fact.Area_Code
join Product
on fact.ProductId=Product.ProductId
group by rollup( State,Product)
order by State;

-- 19. If there is an increase in sales of 5%, calculate the increasedsales.
select Sales, (Sales + Sales * 0.05) as increased_sales
from fact;

-- trainer's answer
select Sales, Sales*1.05 as increasedsales from fact;

-- 20. Find the maximum profit along with the product ID and producttype. 
select Product.ProductId, Product_Type, MAX(Profit) as max_profit
from fact
join Product
on fact.ProductId = Product.ProductId
group by Product.ProductId, Product_Type;

-- trainer's answer
select fact.ProductId,Product_Type,max(Profit) as max_profit from fact
join Product
on fact.ProductId=Product.ProductId
Group by fact.ProductId,Product_Type;


-- 21. Create a stored procedure to fetch the result according to the product typefrom Product Table.
CREATE PROC USP_Get_Products_With_Product_Type
(
@Product_Type varchar(50)
)
AS
BEGIN
	select * from Product where Product_Type = @Product_Type
END;

exec USP_Get_Products_With_Product_Type 'tea';

-- Trainer's answer
/*
-- SYNTAX --
create procedure procedure_name @parameter dataype,.....
as
begin
queries
end*/
create procedure product_pt @pt varchar(50)
as
begin
select * from Product where Product_Type=@pt
end;
exec product_pt 'Tea';

--22. Write a query by creating a condition in which if the total expenses is lessthan 60 
-- then it is a profit or else loss. 

-- trainer's answer
select *,
Case when Total_Expenses<60 then 'Profit'
else 'Loss'
end as profit_loss
from fact;

-- IF ELSE that is IIF can also be used

-------------------------------- Apr 29 -----------------------------

--23. Give the total weekly sales value with the date and product IDdetails. Useroll-up to pull the data in hierarchical order.

-- My answer
select DATEpart(week, date), productid, sum(sales) as total_sales
from fact
group by rollup (DATEPART(week, date), ProductId);

-- as someone asked for coalesce - my answer
select coalesce(DATEPART(WEEK,Date), -100) as weekno, Coalesce(ProductId, -100) as ProductId,sum(Sales) as totalSales from factgroup by rollup(DATEPART(WEEK,Date),ProductId); --   -400 means subtotal


-- Trainer's answer
select DATEPART(WEEK,Date) as weekno,ProductId,sum(Sales) as totalSales from factgroup by rollup(DATEPART(WEEK,Date),ProductId);

-- as someone asked for coalesce
-- this cast gives error
-- select coalesce(DATEPART(WEEK,Date), cast('S_week' as tinyint)) as weekno, Coalesce(ProductId, cast('S_ProductId' as tinyint)) as ProductId,sum(Sales) as totalSales from fact-- group by rollup(DATEPART(WEEK,Date),ProductId);

-- as someone asked for coalesce, corrected one
select coalesce(DATEPART(WEEK,Date), 4) as weekno, Coalesce(ProductId, 4) as ProductId,sum(Sales) as totalSales from factgroup by rollup(DATEPART(WEEK,Date),ProductId); -- 4 means subtotal

-- another implementation
-- as someone asked for coalesce, corrected one
select Coalesce(Cast(DATEPART(WEEK,Date) as varchar),'SWeekNo') as weekno,Coalesce(CAST(ProductId as varchar),'Spid') as ProductId,sum(Sales) as totalSales from factgroup by rollup(DATEPART(WEEK,Date),ProductId);

--24. Apply union and intersection operator on the tables which consist of attribute area code.
select Area_Code from [Location]
union
select Area_Code from fact;

select Area_Code from [Location]
intersect
select Area_Code from fact;

-- Trainer's answer
select Area_Code from factunionSelect area_code from Location;select Area_Code from factintersectSelect area_code from Location;--25. Create a user-defined function for the product table to fetch a particular product type based upon the user’s preference.-- my answercreate function FN_get_products_with_product_type(@ProductType varchar(50))returns tableasreturn 	select * from Product where Product_Type=@ProductType;select * from dbo.FN_get_products_with_product_type('Tea');-- trainer's answercreate function selpt(@pt varchar(50))returns tableasreturn (Select * from Product where Product_Type=@pt);select * from selpt('Coffee');--26. Change the product type from coffee to tea where product IDis 1 and undo it.-- my answer-- using TRAN keyword which is shortform of transactionBEGIN TRANupdate Productset Product_Type = 'Tea'where ProductId = 1;--checkingselect * from Product where ProductId=1;-- rollbackrollback;--checkingselect * from Product where ProductId=1;-- trainer's answerselect * from Product;begin transactionupdate Productset Product_Type='Tea'where ProductId=1 and Product_Type='Coffee';select * from Product;rollback;select * from Product;--27. Display the date, product ID and sales where total expenses are between 100 to 200.select date, ProductId, Sales from fact where Total_Expenses between 100 and 200;-- trainer's answerselect date,ProductId,Sales from factwhere Total_Expenses between 100 and 200;--28. Delete the records in the Product Table for regular type.begin transactiondelete from [Product] where [Type] = 'Regular';select * from [Product];commit;-- trainer's answerselect * from Product;delete from Productwhere Type = 'Regular';--29. Display the ASCII value of the fifth character from the columnProductselect ascii(substring(Product, 5, 1)) as fifth_character_ascii from Product;-- trainer's answerselect Product,ascii(SUBSTRING(Product,5,1)) as AsciiValue from Product;select ascii('A');select ascii('a');